framework:
    messenger: 
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            subscription_email:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: subscription_email_failed
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            subscription_email_failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: subscription_email_failed
                    queues:
                        subscription_email_failed: ~

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            # Symfony\Component\Notifier\Message\ChatMessage: async
            # Symfony\Component\Notifier\Message\SmsMessage: async
            

            # Route your messages to the transports
            App\Message\TenantSubscriptionEmailMessage: subscription_email
